name: eval
channels:
  - defaults
  # - conda-forge
dependencies:
  - python=3.9  # 选择合适的Python版本
  - pip
  - pip:
      - accelerate>=0.12.0
      - datasets>=1.8.0
      - sentencepiece!=0.1.92
      - protobuf
      - rouge-score
      - nltk
      - py7zr
      - torch==2.0
      - evaluate
      - tf-keras
      - wandb
      - bert-score
      - typer[all]
      - omegaconf
      - InstructorEmbedding
      - openai
      - langchain
      - tiktoken
      - thefuzz[speedup]
      - git+https://github.com/huggingface/transformers.git
      - git+https://github.com/google-research/bleurt.git
      # 如果需要安装peft的最新版本，可以取消下面这行的注释
      # - git+https://github.com/huggingface/peft.git
